databases:
  - name: byd_development
    databaseName: byd_development
    user: byd_development_user

services:
  - type: web
    name: BYD (Budget your day)
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: byd_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false